name: Publish

on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/publish.yml
      - core/**

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          submodules: 'recursive'

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: seanmiddleditch/gha-setup-ninja@master
        with:
          version: 1.12.0

      - name: Build
        run: |
          rm -rf $ANDROID_HOME/cmake
          ./gradlew :core:publish -Pversion=${GITHUB_REF##*/}-SNAPSHOT
          ./gradlew :core:publish -Pversion=$(git rev-parse --short "$GITHUB_SHA")
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
